import { describe, expect, it } from "vitest";

import {
  createRitualStaticExport,
  formatRitualStaticExportReport,
  isRitualStaticExportSuccessful,
} from "../../src/data/rituals/db-static-export";
import {
  createRitualDbMirrorDryRun,
  type RitualDbMirrorDryRunRecord,
} from "../../src/data/rituals/db-mirror";
import { sourceBackedRituals } from "../../src/data/rituals/source-backed-rituals";

const generatedAtIso = "2026-06-13T00:00:00.000Z";

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function createExportReport(records: readonly RitualDbMirrorDryRunRecord[]) {
  return createRitualStaticExport({
    ritualDocuments: records.map((record) => record.ritualDocument),
    versionDocuments: records.map((record) => record.versionDocument),
    validationSnapshots: records.map((record) => record.validationSnapshot),
  });
}

function createMirrorRecords(count = 2): RitualDbMirrorDryRunRecord[] {
  const report = createRitualDbMirrorDryRun(
    sourceBackedRituals.slice(0, count),
    { generatedAtIso },
  );

  expect(report.skipped).toEqual([]);
  return report.mirrored;
}

describe("DB-to-TypeScript Ritual static export", () => {
  it("exports reviewed DB versions to deterministic static TypeScript source", () => {
    const records = createMirrorRecords(2).reverse();
    const firstReport = createExportReport(records);
    const secondReport = createExportReport(records);
    const sortedRitualIds = records
      .map((record) => record.ritualId)
      .sort((left, right) => left.localeCompare(right));

    expect(isRitualStaticExportSuccessful(firstReport)).toBe(true);
    expect(firstReport).toEqual(secondReport);
    expect(firstReport.records.map((record) => record.ritualId)).toEqual(
      sortedRitualIds,
    );
    expect(firstReport.sourceText).toContain(
      "Generated by scripts/export-db-rituals-to-static.ts.",
    );
    expect(firstReport.sourceText).toContain(
      "export const sourceBackedRituals: Ritual[]",
    );
    expect(firstReport.sourceText).not.toContain("undefined");
  });

  it("validates before export and refuses invalid published versions", () => {
    const [record] = createMirrorRecords(1);
    const invalidRecord = clone(record);

    invalidRecord.versionDocument.contentHash =
      "fnv1a128:00000000000000000000000000000000";

    const report = createExportReport([invalidRecord]);

    expect(isRitualStaticExportSuccessful(report)).toBe(false);
    expect(report.records).toEqual([]);
    expect(report.sourceText).toBe("");
    expect(report.skipped[0].reasons.map((reason) => reason.path)).toContain(
      "contentHash",
    );
  });

  it("refuses unpublished Ritual pointers", () => {
    const [record] = createMirrorRecords(1);
    const unpublishedRecord = clone(record);

    delete unpublishedRecord.ritualDocument.publishedVersionId;

    const report = createExportReport([unpublishedRecord]);

    expect(isRitualStaticExportSuccessful(report)).toBe(false);
    expect(report.records).toEqual([]);
    expect(report.skipped[0].reasons.map((reason) => reason.path)).toContain(
      "ritualDocument.publishedVersionId",
    );
  });

  it("refuses unreviewed DB Ritual pointers", () => {
    const [record] = createMirrorRecords(1);
    const draftRecord = clone(record);

    draftRecord.ritualDocument.lifecycle.state = "draft";

    const report = createExportReport([draftRecord]);

    expect(isRitualStaticExportSuccessful(report)).toBe(false);
    expect(report.records).toEqual([]);
    expect(report.skipped[0].reasons.map((reason) => reason.path)).toContain(
      "ritualDocument.lifecycle.state",
    );
  });

  it("refuses records without a valid validation snapshot", () => {
    const [record] = createMirrorRecords(1);
    const report = createRitualStaticExport({
      ritualDocuments: [record.ritualDocument],
      versionDocuments: [record.versionDocument],
      validationSnapshots: [],
    });

    expect(isRitualStaticExportSuccessful(report)).toBe(false);
    expect(report.records).toEqual([]);
    expect(report.skipped[0].reasons.map((reason) => reason.path)).toContain(
      "ritualDocument.latestValidationSnapshotId",
    );
  });

  it("formats a PR-reviewable export report", () => {
    const report = createExportReport(createMirrorRecords(1));
    const formatted = formatRitualStaticExportReport(report);

    expect(formatted).toContain("DB-to-TypeScript Ritual static export");
    expect(formatted).toContain(
      "Target file: src/data/rituals/source-backed-rituals.ts",
    );
    expect(formatted).toContain("Firestore writes: no");
    expect(formatted).toContain("Export result: pass");
  });
});
